#include "menu.h"


static void TEMP_MENU(void);
static void TEMP_PARAM_MENU(void);

static void MOTOR_MENU(void);
static void MOTOR_TEST_MENU(void);
static void MOTOR_RUN_MENU(void);

static void MOTOR_SPEED_MENU(void);
static void MOTOR_SPEED_PARAM_MENU(void);

static void PARAM_SET_MENU(void);

code Menu_t menu_list[10] = {
    /* 一级菜单 */
    {TEMP_MENU_ID,MOTOR_MENU_ID,PARAM_SET_MENU_ID,TEMP_PARAM_MENU_ID,NULL_MENU_ID,TEMP_MENU},
    {MOTOR_MENU_ID,MOTOR_SPEED_MENU_ID,TEMP_MENU_ID,MOTOR_TEST_MENU_ID,NULL_MENU_ID,MOTOR_MENU},
    {MOTOR_SPEED_MENU_ID,PARAM_SET_MENU_ID,MOTOR_MENU_ID,NULL_MENU_ID,MOTOR_SPEED_PARAM_MENU_ID,MOTOR_SPEED_MENU},
    {PARAM_SET_MENU_ID,TEMP_MENU_ID,MOTOR_SPEED_MENU_ID,NULL_MENU_ID,NULL_MENU_ID,PARAM_SET_MENU},
    /* 二级菜单 */
    {TEMP_PARAM_MENU_ID,NULL_MENU_ID,NULL_MENU_ID,NULL_MENU_ID,TEMP_MENU_ID,TEMP_PARAM_MENU},
    {MOTOR_TEST_MENU_ID,NULL_MENU_ID,NULL_MENU_ID,MOTOR_RUN_MENU_ID,MOTOR_MENU_ID,MOTOR_TEST_MENU},
    {MOTOR_SPEED_PARAM_MENU_ID,NULL_MENU_ID,NULL_MENU_ID,NULL_MENU_ID,MOTOR_SPEED_MENU_ID,MOTOR_SPEED_PARAM_MENU},
    /* 三级菜单 */
    {MOTOR_RUN_MENU_ID,NULL_MENU_ID,NULL_MENU_ID,NULL_MENU_ID,MOTOR_TEST_MENU_ID,MOTOR_RUN_MENU},
};

static void TEMP_MENU(void)
{

}

static void TEMP_PARAM_MENU(void)
{

}

static void MOTOR_MENU(void)
{

}
static void MOTOR_TEST_MENU(void)
{

}

static void MOTOR_RUN_MENU(void)
{

}

static void MOTOR_SPEED_MENU(void)
{

}

static void MOTOR_SPEED_PARAM_MENU(void)
{

}

static void PARAM_SET_MENU(void)
{

}